#!/usr/bin/env sh
# Author: javy liu
#Date & Time: 2021-10-20 10:36:34
#Description:create a rails app by the rapp_in_docker


docker-compose run --rm --no-deps web sh <<HERE
  bundle exec rails new . --force --database=postgresql -B
  bundle config set --local path 'vendor/bundle'
  sed -i 's!rubygems.org!gems.ruby-china.com!' Gemfile
  bundle install
  bundle exec rails webpacker:install
  source .env
  sed -i -r '/username: app|password: </d;/encoding:/a\
    host: db\n  username: '"${PQ_USER}"'\n  password: '"${PQ_PASSWORD}"  config/database.yml

HERE


docker-compose run --rm web bundle exec rails db:create
